apiVersion: v1
clusters:
- cluster:
    #certificate-authority: /root/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 14 Jun 2022 18:37:03 UTC
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: http://minikube:<htpasswd_password>@k8s.truetech.solutions:8080 #remote Ip in domain place
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 14 Jun 2022 18:37:03 UTC
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    #client-certificate: /root/.minikube/profiles/minikube/client.crt
    #client-key: /root/.minikube/profiles/minikube/client.key